language: python

python: 2.7

sudo: false

cache: pip

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/

install:
  - pip install ansible

script:
  - ansible-playbook -i tests/inventory --syntax-check tests/test.yml
