- name: Generate Cloudflare Origin CA
  shell: "cfca getcert \
    -hostnames {{ site_hosts | union(multisite_subdomains_wildcards) | join(',') }} \
    -key-out {{ item.key | quote }}.key \
    -certificate-out {{ item.key | quote }}.pem"
  args:
    executable: "/bin/bash"
    chdir: "{{ nginx_ssl_path }}/cloudflare-origin-ca"
    creates: "{{ item.key }}.*"
  environment:
    CF_API_KEY: "{{ vault_cloudflare_origin_ca_key | mandatory }}"
  no_log: true
  with_dict: "{{ wordpress_sites }}"
  when: item.key in sites_using_cloudflare_origin_ca
  notify: reload nginx
