---
- fail:
    msg: No site is using Cloudflare Origin CA
  when: sites_using_cloudflare_origin_ca | count < 1

- fail:
    msg: vault_cloudflare_origin_ca_key is not defined
  when: vault_cloudflare_origin_ca_key is not defined

- fail:
    msg: "{{ item.key }} is using Cloudflare Origin CA but OCSP stapling is enabled"
  when:
    - site_uses_cloudflare_origin_ca
    - ssl_stapling_enabled
  with_dict: "{{ wordpress_sites }}"

- include: setup.yml
- include: certificates.yml
- include: nginx.yml
