---
- name: Ensure includes.d directories exist
  file:
    path: "{{ nginx_path }}/includes.d/{{ item.key }}"
    state: directory
    mode: 0755
  when: site_uses_cloudflare_origin_ca
  with_dict: "{{ wordpress_sites }}"

- name: Template Nginx SSL directives out to includes.d
  template:
    src: cloudflare-origin-ca.conf.j2
    dest: "{{ nginx_path }}/includes.d/{{ item.key }}/cloudflare-origin-ca.conf"
  when: site_uses_cloudflare_origin_ca
  with_dict: "{{ wordpress_sites }}"
  notify: reload nginx
