---
- name: Ensure includes.d directories exist
  file:
    path: "{{ nginx_path }}/includes.d/{{ item.key }}"
    state: directory
    mode: 0755
  with_dict: "{{ wordpress_sites }}"
  when: item.key in sites_using_cloudflare_origin_ca

- name: Template Nginx SSL directives out to includes.d
  template:
    src: cloudflare-origin-ca.conf.j2
    dest: "{{ nginx_path }}/includes.d/{{ item.key }}/cloudflare-origin-ca.conf"
  with_dict: "{{ wordpress_sites }}"
  when: item.key in sites_using_cloudflare_origin_ca
  notify: reload nginx
