---
- name: Add Cloudflare key
  apt_key:
    url: 'https://pkg.cloudflare.com/pubkey.gpg'

- name: Add Cloudflare PPA
  apt_repository:
    repo: 'deb http://pkg.cloudflare.com/ xenial main'

- name: Install CFCA
  apt:
    name: cfca
    state: "{{ cfca_package_state }}"
    update_cache: yes

- name: Create directoriy and set permission
  file:
    path: "{{ nginx_ssl_path }}/cloudflare-origin-ca"
    mode: 0700
    state: directory
